### ISSUE TITLE
Профессор как Президент?

### ISSUE THREAD

**Issue by ulysses4ever** [siamezzze/thesis#1]
Заглавной буквы, мне кажется, там не требуется (это титульный лист).

**Comment by siamezzze** [comment]
Мм, да. Вообще раз уж там сокращения дальше, наверное, нужно и это как "проф."?

**Comment by ulysses4ever** [comment]
Звание целиком это вполне распространённый вариант, так что необязательно
сокращать. Степень просто длинная очень.

**Comment by siamezzze** [comment]
Спасибо.
